title: Kirill Samaray
logo: "/images/WhatsApp Image 2024-07-22 at 20.26.35.jpeg?raw=true"
description: > 
  Experienced Data Analyst with a decade of expertise across Data Analytics, Educational Management, and Oil & Gas industries, including managerial experience on international projects. Recently completed a Master’s in Data Analytics from the University of Akron in the U.S. through the Fulbright program, specializing in Information Systems Management. Proficient in Python, SQL, R, C#, Tableau, Machine Learning, and Visual Studio, I excel at converting complex datasets into actionable insights to drive strategic decision-making and optimize processes. My portfolio showcases advanced analytics projects, underscoring a commitment to data-driven solutions and impactful business outcomes.  <br>  
  
  <br>  
  
  <a href="https://www.linkedin.com/in/kirill-samaray-8b43b414a">View My LinkedIn Profile</a>  
  
theme: jekyll-theme-minimal
google_analytics: UA-252593385-1










