# Website Configuration
title: Kirill Samaray
logo: "/images/Photo 2022.jpg?raw=true"
description: |
  10 years of experience in Oil & Gas and Education.
  2 years of Management experience with excessive international exposure.
  Currently pursuing Master's Degree in Business Analytics, Information Systems Management specialization.

---
  
  Strong technical skills in R, SQL, Machine Learning, Database Management, Mongo DB, JMP.
  Possesses Master's Degree in Engineering and Shipping Operations. International Fulbright Scholar.

---
  
  [View My LinkedIn Profile](https://www.linkedin.com/in/kirill-samaray-8b43b414a)

# Jekyll Configuration
theme: jekyll-theme-minimal
google_analytics: G-XXBSPVBYP9








