title: Kirill Samaray
logo: "/images/Photo 2022.jpg?raw=true"
description: > 
  10 years of experience in Oil & Gas and Education, including 2 years of Management experience with extensive international exposure. Pursuing a Master's Degree in Business Analytics with a specialization in Information Systems Management.
  Strong technical skills in R, SQL, Machine Learning, Database Management, Mongo DB, and JMP. Holds a Master's Degree in Engineering and Shipping Operations and is an International Fulbright Scholar.  
  
  <a href="https://www.linkedin.com/in/kirill-samaray-8b43b414a">View My LinkedIn Profile</a>  
  
  
  
theme: jekyll-theme-minimal
google_analytics: G-XXBSPVBYP9








