title: Kirill Samaray
logo: "/images/Photo 2022.jpg?raw=true"
description: > 
  10 years of experience in Management and Oil & Gas with extensive international exposure. A Fulbright Scholar, Pursuing a Master's Degree in Business Analytics with a specialization in Information Systems Management.
  Strong technical skills in R, SQL, Machine Learning, Database Management, Mongo DB, and JMP. Hold a Master's Degree in Engineering and Shipping Operations.  
  
  <a href="https://www.linkedin.com/in/kirill-samaray-8b43b414a">View My LinkedIn Profile</a>  
  
  
  
theme: jekyll-theme-minimal
google_analytics: G-XXBSPVBYP9  

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXBSPVBYP9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXBSPVBYP9');
</script>








